/**
 * @file Fan.h
 * @brief Fan Module Interface
 * @details Voltage-based PWM fan control using ESP32 LEDC.
 *          Controls 2-pin or 3-pin DC fan by PWM switching the power supply
 *          line through NPN + P-channel MOSFET circuit.
 *
 *          Tachometer feedback is optional — controlled by FAN_TACH_ENABLED
 *          in Fan_Cfg.h. When disabled, Fan__IsFailed() detects software/driver
 *          faults only. When enabled, it detects real physical stall/disconnect.
 *
 * @note Edit Fan_Cfg.h to change pin, voltage thresholds, and tach settings.
 *       Do NOT edit this file or Fan.cpp for configuration changes.
 *
 * Usage:
 *   Fan__Init();                 // call once in setup()
 *   Fan__SetVoltage(0.0f);       // fan OFF
 *   Fan__SetVoltage(2.0f);       // medium speed
 *   Fan__SetVoltage(5.0f);       // full speed
 *   Fan__Off();                  // force fan off
 *   Fan__IsFailed();             // true = fan not spinning when it should be
 *   Fan__GetRPM();               // measured RPM (0 if tach disabled)
 */

#ifndef FAN_H
#define FAN_H

#include <stdint.h>
#include <stdbool.h>
#include "Fan_Cfg.h"

/*==============================================================================
 *                          FUNCTION PROTOTYPES
 *============================================================================*/

/**
 * @brief Initialize the fan module — call once in setup()
 * @details Sets up PWM output. If FAN_TACH_ENABLED=1, also configures
 *          tachometer GPIO and attaches interrupt for pulse counting.
 */
void Fan__Init(void);

/**
 * @brief Set fan speed by equivalent voltage
 * @param voltage Desired voltage in volts (0.0 to FAN_SUPPLY_VOLTAGE)
 * @details
 *   voltage <= FAN_VOLT_OFF   → fan OFF
 *   FAN_VOLT_START to
 *   FAN_VOLT_FULL             → linear speed ramp
 *   voltage >= FAN_VOLT_FULL  → full speed
 */
void Fan__SetVoltage(float voltage);

/**
 * @brief Force fan off regardless of voltage
 */
void Fan__Off(void);

/**
 * @brief Get current logical duty cycle (0=off, 255=full)
 * @return uint8_t current duty
 */
uint8_t Fan__GetDuty(void);

/**
 * @brief Periodic fan update — call every loop() cycle
 * @details Required for tachometer RPM calculation and stall detection timing.
 *          Safe to call when FAN_TACH_ENABLED=0 (does nothing in that case).
 */
void Fan__Handler(void);

/**
 * @brief Check if the fan has failed
 * @details When FAN_TACH_ENABLED=0 (2-wire fan, current hardware):
 *            Returns true if duty > 0 but reads back as 0 (software fault).
 *          When FAN_TACH_ENABLED=1 (3-wire fan, future hardware):
 *            Returns true if duty > 0 AND measured RPM == 0 after
 *            FAN_STALL_DETECT_MS — real physical stall/disconnect detection.
 * @return true if fan failure detected, false if operating normally
 */
bool Fan__IsFailed(void);

/**
 * @brief Get measured fan RPM
 * @details Returns 0 if FAN_TACH_ENABLED=0 or fan is commanded OFF.
 *          Updated every FAN_TACH_MEASURE_MS when tach is enabled.
 * @return uint16_t measured RPM
 */
uint16_t Fan__GetRPM(void);

/**
 * @brief Set PWM frequency at runtime (e.g. from BLE control)
 * @param hz Desired frequency in Hz, clamped to FAN_FREQ_MIN_HZ..FAN_FREQ_MAX_HZ
 */
void Fan__SetFrequency(uint32_t hz);

/**
 * @brief Get current PWM frequency
 * @return uint32_t current frequency in Hz
 */
uint32_t Fan__GetFrequency(void);

/**
 * @brief Set fan speed by direct duty percent (0-100%)
 * @details Bypasses the voltage curve used by Fan__SetVoltage() — use for
 *          direct BLE/manual control where the app sends an exact percent.
 * @param percent Desired duty 0-100
 */
void Fan__SetDutyPercent(uint8_t percent);

#endif /* FAN_H */